apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: app-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app
            image: eu.gcr.io/thesis-project-111/thesis-app:59292779
            command: ["python3", "monitor.py"]
          restartPolicy: OnFailure
